//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceProveedor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdproveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_provField;
        
        private int Numero_provField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Idproveedor {
            get {
                return this.IdproveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdproveedorField, value) != true)) {
                    this.IdproveedorField = value;
                    this.RaisePropertyChanged("Idproveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre_prov {
            get {
                return this.Nombre_provField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_provField, value) != true)) {
                    this.Nombre_provField = value;
                    this.RaisePropertyChanged("Nombre_prov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Numero_prov {
            get {
                return this.Numero_provField;
            }
            set {
                if ((this.Numero_provField.Equals(value) != true)) {
                    this.Numero_provField = value;
                    this.RaisePropertyChanged("Numero_prov");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProveedor.WebServiceProveedorSoap")]
    public interface WebServiceProveedorSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento proveedor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioinsertarProveedor", ReplyAction="*")]
        CapaGUI.ServiceProveedor.ServicioinsertarProveedorResponse ServicioinsertarProveedor(CapaGUI.ServiceProveedor.ServicioinsertarProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioinsertarProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServicioinsertarProveedorResponse> ServicioinsertarProveedorAsync(CapaGUI.ServiceProveedor.ServicioinsertarProveedorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idproveedor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiciobuscaProv", ReplyAction="*")]
        CapaGUI.ServiceProveedor.ServiciobuscaProvResponse ServiciobuscaProv(CapaGUI.ServiceProveedor.ServiciobuscaProvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiciobuscaProv", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServiciobuscaProvResponse> ServiciobuscaProvAsync(CapaGUI.ServiceProveedor.ServiciobuscaProvRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idproveedor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiciobuscaConcidencia", ReplyAction="*")]
        CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaResponse ServiciobuscaConcidencia(CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiciobuscaConcidencia", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaResponse> ServiciobuscaConcidenciaAsync(CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IDaborrar del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioeliminarProv", ReplyAction="*")]
        CapaGUI.ServiceProveedor.ServicioeliminarProvResponse ServicioeliminarProv(CapaGUI.ServiceProveedor.ServicioeliminarProvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioeliminarProv", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServicioeliminarProvResponse> ServicioeliminarProvAsync(CapaGUI.ServiceProveedor.ServicioeliminarProvRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento proveedor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServcioactualizarProv", ReplyAction="*")]
        CapaGUI.ServiceProveedor.ServcioactualizarProvResponse ServcioactualizarProv(CapaGUI.ServiceProveedor.ServcioactualizarProvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServcioactualizarProv", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServcioactualizarProvResponse> ServcioactualizarProvAsync(CapaGUI.ServiceProveedor.ServcioactualizarProvRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioinsertarProveedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioinsertarProveedor", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceProveedor.ServicioinsertarProveedorRequestBody Body;
        
        public ServicioinsertarProveedorRequest() {
        }
        
        public ServicioinsertarProveedorRequest(CapaGUI.ServiceProveedor.ServicioinsertarProveedorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioinsertarProveedorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceProveedor.Proveedor proveedor;
        
        public ServicioinsertarProveedorRequestBody() {
        }
        
        public ServicioinsertarProveedorRequestBody(CapaGUI.ServiceProveedor.Proveedor proveedor) {
            this.proveedor = proveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioinsertarProveedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioinsertarProveedorResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceProveedor.ServicioinsertarProveedorResponseBody Body;
        
        public ServicioinsertarProveedorResponse() {
        }
        
        public ServicioinsertarProveedorResponse(CapaGUI.ServiceProveedor.ServicioinsertarProveedorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioinsertarProveedorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ServicioinsertarProveedorResult;
        
        public ServicioinsertarProveedorResponseBody() {
        }
        
        public ServicioinsertarProveedorResponseBody(bool ServicioinsertarProveedorResult) {
            this.ServicioinsertarProveedorResult = ServicioinsertarProveedorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiciobuscaProvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiciobuscaProv", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceProveedor.ServiciobuscaProvRequestBody Body;
        
        public ServiciobuscaProvRequest() {
        }
        
        public ServiciobuscaProvRequest(CapaGUI.ServiceProveedor.ServiciobuscaProvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiciobuscaProvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idproveedor;
        
        public ServiciobuscaProvRequestBody() {
        }
        
        public ServiciobuscaProvRequestBody(string idproveedor) {
            this.idproveedor = idproveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiciobuscaProvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiciobuscaProvResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceProveedor.ServiciobuscaProvResponseBody Body;
        
        public ServiciobuscaProvResponse() {
        }
        
        public ServiciobuscaProvResponse(CapaGUI.ServiceProveedor.ServiciobuscaProvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiciobuscaProvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceProveedor.Proveedor ServiciobuscaProvResult;
        
        public ServiciobuscaProvResponseBody() {
        }
        
        public ServiciobuscaProvResponseBody(CapaGUI.ServiceProveedor.Proveedor ServiciobuscaProvResult) {
            this.ServiciobuscaProvResult = ServiciobuscaProvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiciobuscaConcidenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiciobuscaConcidencia", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaRequestBody Body;
        
        public ServiciobuscaConcidenciaRequest() {
        }
        
        public ServiciobuscaConcidenciaRequest(CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiciobuscaConcidenciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idproveedor;
        
        public ServiciobuscaConcidenciaRequestBody() {
        }
        
        public ServiciobuscaConcidenciaRequestBody(string idproveedor) {
            this.idproveedor = idproveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiciobuscaConcidenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiciobuscaConcidenciaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaResponseBody Body;
        
        public ServiciobuscaConcidenciaResponse() {
        }
        
        public ServiciobuscaConcidenciaResponse(CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiciobuscaConcidenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceProveedor.Proveedor ServiciobuscaConcidenciaResult;
        
        public ServiciobuscaConcidenciaResponseBody() {
        }
        
        public ServiciobuscaConcidenciaResponseBody(CapaGUI.ServiceProveedor.Proveedor ServiciobuscaConcidenciaResult) {
            this.ServiciobuscaConcidenciaResult = ServiciobuscaConcidenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioeliminarProvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioeliminarProv", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceProveedor.ServicioeliminarProvRequestBody Body;
        
        public ServicioeliminarProvRequest() {
        }
        
        public ServicioeliminarProvRequest(CapaGUI.ServiceProveedor.ServicioeliminarProvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServicioeliminarProvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDaborrar;
        
        public ServicioeliminarProvRequestBody() {
        }
        
        public ServicioeliminarProvRequestBody(string IDaborrar) {
            this.IDaborrar = IDaborrar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServicioeliminarProvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServicioeliminarProvResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceProveedor.ServicioeliminarProvResponseBody Body;
        
        public ServicioeliminarProvResponse() {
        }
        
        public ServicioeliminarProvResponse(CapaGUI.ServiceProveedor.ServicioeliminarProvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ServicioeliminarProvResponseBody {
        
        public ServicioeliminarProvResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServcioactualizarProvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServcioactualizarProv", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceProveedor.ServcioactualizarProvRequestBody Body;
        
        public ServcioactualizarProvRequest() {
        }
        
        public ServcioactualizarProvRequest(CapaGUI.ServiceProveedor.ServcioactualizarProvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServcioactualizarProvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceProveedor.Proveedor proveedor;
        
        public ServcioactualizarProvRequestBody() {
        }
        
        public ServcioactualizarProvRequestBody(CapaGUI.ServiceProveedor.Proveedor proveedor) {
            this.proveedor = proveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServcioactualizarProvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServcioactualizarProvResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceProveedor.ServcioactualizarProvResponseBody Body;
        
        public ServcioactualizarProvResponse() {
        }
        
        public ServcioactualizarProvResponse(CapaGUI.ServiceProveedor.ServcioactualizarProvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ServcioactualizarProvResponseBody {
        
        public ServcioactualizarProvResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProveedorSoapChannel : CapaGUI.ServiceProveedor.WebServiceProveedorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProveedorSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceProveedor.WebServiceProveedorSoap>, CapaGUI.ServiceProveedor.WebServiceProveedorSoap {
        
        public WebServiceProveedorSoapClient() {
        }
        
        public WebServiceProveedorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProveedorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProveedorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProveedorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceProveedor.ServicioinsertarProveedorResponse CapaGUI.ServiceProveedor.WebServiceProveedorSoap.ServicioinsertarProveedor(CapaGUI.ServiceProveedor.ServicioinsertarProveedorRequest request) {
            return base.Channel.ServicioinsertarProveedor(request);
        }
        
        public bool ServicioinsertarProveedor(CapaGUI.ServiceProveedor.Proveedor proveedor) {
            CapaGUI.ServiceProveedor.ServicioinsertarProveedorRequest inValue = new CapaGUI.ServiceProveedor.ServicioinsertarProveedorRequest();
            inValue.Body = new CapaGUI.ServiceProveedor.ServicioinsertarProveedorRequestBody();
            inValue.Body.proveedor = proveedor;
            CapaGUI.ServiceProveedor.ServicioinsertarProveedorResponse retVal = ((CapaGUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServicioinsertarProveedor(inValue);
            return retVal.Body.ServicioinsertarProveedorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServicioinsertarProveedorResponse> CapaGUI.ServiceProveedor.WebServiceProveedorSoap.ServicioinsertarProveedorAsync(CapaGUI.ServiceProveedor.ServicioinsertarProveedorRequest request) {
            return base.Channel.ServicioinsertarProveedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServicioinsertarProveedorResponse> ServicioinsertarProveedorAsync(CapaGUI.ServiceProveedor.Proveedor proveedor) {
            CapaGUI.ServiceProveedor.ServicioinsertarProveedorRequest inValue = new CapaGUI.ServiceProveedor.ServicioinsertarProveedorRequest();
            inValue.Body = new CapaGUI.ServiceProveedor.ServicioinsertarProveedorRequestBody();
            inValue.Body.proveedor = proveedor;
            return ((CapaGUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServicioinsertarProveedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceProveedor.ServiciobuscaProvResponse CapaGUI.ServiceProveedor.WebServiceProveedorSoap.ServiciobuscaProv(CapaGUI.ServiceProveedor.ServiciobuscaProvRequest request) {
            return base.Channel.ServiciobuscaProv(request);
        }
        
        public CapaGUI.ServiceProveedor.Proveedor ServiciobuscaProv(string idproveedor) {
            CapaGUI.ServiceProveedor.ServiciobuscaProvRequest inValue = new CapaGUI.ServiceProveedor.ServiciobuscaProvRequest();
            inValue.Body = new CapaGUI.ServiceProveedor.ServiciobuscaProvRequestBody();
            inValue.Body.idproveedor = idproveedor;
            CapaGUI.ServiceProveedor.ServiciobuscaProvResponse retVal = ((CapaGUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServiciobuscaProv(inValue);
            return retVal.Body.ServiciobuscaProvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServiciobuscaProvResponse> CapaGUI.ServiceProveedor.WebServiceProveedorSoap.ServiciobuscaProvAsync(CapaGUI.ServiceProveedor.ServiciobuscaProvRequest request) {
            return base.Channel.ServiciobuscaProvAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServiciobuscaProvResponse> ServiciobuscaProvAsync(string idproveedor) {
            CapaGUI.ServiceProveedor.ServiciobuscaProvRequest inValue = new CapaGUI.ServiceProveedor.ServiciobuscaProvRequest();
            inValue.Body = new CapaGUI.ServiceProveedor.ServiciobuscaProvRequestBody();
            inValue.Body.idproveedor = idproveedor;
            return ((CapaGUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServiciobuscaProvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaResponse CapaGUI.ServiceProveedor.WebServiceProveedorSoap.ServiciobuscaConcidencia(CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaRequest request) {
            return base.Channel.ServiciobuscaConcidencia(request);
        }
        
        public CapaGUI.ServiceProveedor.Proveedor ServiciobuscaConcidencia(string idproveedor) {
            CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaRequest inValue = new CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaRequest();
            inValue.Body = new CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaRequestBody();
            inValue.Body.idproveedor = idproveedor;
            CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaResponse retVal = ((CapaGUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServiciobuscaConcidencia(inValue);
            return retVal.Body.ServiciobuscaConcidenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaResponse> CapaGUI.ServiceProveedor.WebServiceProveedorSoap.ServiciobuscaConcidenciaAsync(CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaRequest request) {
            return base.Channel.ServiciobuscaConcidenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaResponse> ServiciobuscaConcidenciaAsync(string idproveedor) {
            CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaRequest inValue = new CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaRequest();
            inValue.Body = new CapaGUI.ServiceProveedor.ServiciobuscaConcidenciaRequestBody();
            inValue.Body.idproveedor = idproveedor;
            return ((CapaGUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServiciobuscaConcidenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceProveedor.ServicioeliminarProvResponse CapaGUI.ServiceProveedor.WebServiceProveedorSoap.ServicioeliminarProv(CapaGUI.ServiceProveedor.ServicioeliminarProvRequest request) {
            return base.Channel.ServicioeliminarProv(request);
        }
        
        public void ServicioeliminarProv(string IDaborrar) {
            CapaGUI.ServiceProveedor.ServicioeliminarProvRequest inValue = new CapaGUI.ServiceProveedor.ServicioeliminarProvRequest();
            inValue.Body = new CapaGUI.ServiceProveedor.ServicioeliminarProvRequestBody();
            inValue.Body.IDaborrar = IDaborrar;
            CapaGUI.ServiceProveedor.ServicioeliminarProvResponse retVal = ((CapaGUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServicioeliminarProv(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServicioeliminarProvResponse> CapaGUI.ServiceProveedor.WebServiceProveedorSoap.ServicioeliminarProvAsync(CapaGUI.ServiceProveedor.ServicioeliminarProvRequest request) {
            return base.Channel.ServicioeliminarProvAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServicioeliminarProvResponse> ServicioeliminarProvAsync(string IDaborrar) {
            CapaGUI.ServiceProveedor.ServicioeliminarProvRequest inValue = new CapaGUI.ServiceProveedor.ServicioeliminarProvRequest();
            inValue.Body = new CapaGUI.ServiceProveedor.ServicioeliminarProvRequestBody();
            inValue.Body.IDaborrar = IDaborrar;
            return ((CapaGUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServicioeliminarProvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceProveedor.ServcioactualizarProvResponse CapaGUI.ServiceProveedor.WebServiceProveedorSoap.ServcioactualizarProv(CapaGUI.ServiceProveedor.ServcioactualizarProvRequest request) {
            return base.Channel.ServcioactualizarProv(request);
        }
        
        public void ServcioactualizarProv(CapaGUI.ServiceProveedor.Proveedor proveedor) {
            CapaGUI.ServiceProveedor.ServcioactualizarProvRequest inValue = new CapaGUI.ServiceProveedor.ServcioactualizarProvRequest();
            inValue.Body = new CapaGUI.ServiceProveedor.ServcioactualizarProvRequestBody();
            inValue.Body.proveedor = proveedor;
            CapaGUI.ServiceProveedor.ServcioactualizarProvResponse retVal = ((CapaGUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServcioactualizarProv(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServcioactualizarProvResponse> CapaGUI.ServiceProveedor.WebServiceProveedorSoap.ServcioactualizarProvAsync(CapaGUI.ServiceProveedor.ServcioactualizarProvRequest request) {
            return base.Channel.ServcioactualizarProvAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceProveedor.ServcioactualizarProvResponse> ServcioactualizarProvAsync(CapaGUI.ServiceProveedor.Proveedor proveedor) {
            CapaGUI.ServiceProveedor.ServcioactualizarProvRequest inValue = new CapaGUI.ServiceProveedor.ServcioactualizarProvRequest();
            inValue.Body = new CapaGUI.ServiceProveedor.ServcioactualizarProvRequestBody();
            inValue.Body.proveedor = proveedor;
            return ((CapaGUI.ServiceProveedor.WebServiceProveedorSoap)(this)).ServcioactualizarProvAsync(inValue);
        }
    }
}
