//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceProducto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducto.WebServiceProductoSoap")]
    public interface WebServiceProductoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Serviceinsertarproducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Serviceinsertarproducto(CapaGUI.ServiceProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Serviceinsertarproducto", ReplyAction="*")]
        System.Threading.Tasks.Task ServiceinsertarproductoAsync(CapaGUI.ServiceProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicebuscaProv", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceProducto.Producto ServicebuscaProv(string producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicebuscaProv", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceProducto.Producto> ServicebuscaProvAsync(string producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceeliminarProv", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ServiceeliminarProv(string IDaborrar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceeliminarProv", ReplyAction="*")]
        System.Threading.Tasks.Task ServiceeliminarProvAsync(string IDaborrar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceactualizarProv", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ServiceactualizarProv(CapaGUI.ServiceProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceactualizarProv", ReplyAction="*")]
        System.Threading.Tasks.Task ServiceactualizarProvAsync(CapaGUI.ServiceProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGetMinDiasV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ServiceGetMinDiasV();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGetMinDiasV", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ServiceGetMinDiasVAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetName(int diasv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetNameAsync(int diasv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGetCantidadP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ServiceGetCantidadP(string idproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGetCantidadP", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ServiceGetCantidadPAsync(string idproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSetCantidadP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ServiceSetCantidadP(string idproducto, int newcantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceSetCantidadP", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ServiceSetCantidadPAsync(string idproducto, int newcantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGetProductMasVendido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceProducto.Producto ServiceGetProductMasVendido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGetProductMasVendido", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceProducto.Producto> ServiceGetProductMasVendidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGetClienteConMasCompras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceProducto.Producto ServiceGetClienteConMasCompras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGetClienteConMasCompras", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceProducto.Producto> ServiceGetClienteConMasComprasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGetConsultaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ServiceGetConsultaProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceGetConsultaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ServiceGetConsultaProductoAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idproductoField;
        
        private int precio_unitarioField;
        
        private int cantidadField;
        
        private int dias_vencimientoField;
        
        private string idproveedorField;
        
        private string tipo_productoField;
        
        private string caracteristicaField;
        
        private string marcaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Idproducto {
            get {
                return this.idproductoField;
            }
            set {
                this.idproductoField = value;
                this.RaisePropertyChanged("Idproducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Precio_unitario {
            get {
                return this.precio_unitarioField;
            }
            set {
                this.precio_unitarioField = value;
                this.RaisePropertyChanged("Precio_unitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Dias_vencimiento {
            get {
                return this.dias_vencimientoField;
            }
            set {
                this.dias_vencimientoField = value;
                this.RaisePropertyChanged("Dias_vencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Idproveedor {
            get {
                return this.idproveedorField;
            }
            set {
                this.idproveedorField = value;
                this.RaisePropertyChanged("Idproveedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Tipo_producto {
            get {
                return this.tipo_productoField;
            }
            set {
                this.tipo_productoField = value;
                this.RaisePropertyChanged("Tipo_producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Caracteristica {
            get {
                return this.caracteristicaField;
            }
            set {
                this.caracteristicaField = value;
                this.RaisePropertyChanged("Caracteristica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("Marca");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProductoSoapChannel : CapaGUI.ServiceProducto.WebServiceProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProductoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceProducto.WebServiceProductoSoap>, CapaGUI.ServiceProducto.WebServiceProductoSoap {
        
        public WebServiceProductoSoapClient() {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Serviceinsertarproducto(CapaGUI.ServiceProducto.Producto producto) {
            base.Channel.Serviceinsertarproducto(producto);
        }
        
        public System.Threading.Tasks.Task ServiceinsertarproductoAsync(CapaGUI.ServiceProducto.Producto producto) {
            return base.Channel.ServiceinsertarproductoAsync(producto);
        }
        
        public CapaGUI.ServiceProducto.Producto ServicebuscaProv(string producto) {
            return base.Channel.ServicebuscaProv(producto);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceProducto.Producto> ServicebuscaProvAsync(string producto) {
            return base.Channel.ServicebuscaProvAsync(producto);
        }
        
        public void ServiceeliminarProv(string IDaborrar) {
            base.Channel.ServiceeliminarProv(IDaborrar);
        }
        
        public System.Threading.Tasks.Task ServiceeliminarProvAsync(string IDaborrar) {
            return base.Channel.ServiceeliminarProvAsync(IDaborrar);
        }
        
        public void ServiceactualizarProv(CapaGUI.ServiceProducto.Producto producto) {
            base.Channel.ServiceactualizarProv(producto);
        }
        
        public System.Threading.Tasks.Task ServiceactualizarProvAsync(CapaGUI.ServiceProducto.Producto producto) {
            return base.Channel.ServiceactualizarProvAsync(producto);
        }
        
        public int ServiceGetMinDiasV() {
            return base.Channel.ServiceGetMinDiasV();
        }
        
        public System.Threading.Tasks.Task<int> ServiceGetMinDiasVAsync() {
            return base.Channel.ServiceGetMinDiasVAsync();
        }
        
        public string GetName(int diasv) {
            return base.Channel.GetName(diasv);
        }
        
        public System.Threading.Tasks.Task<string> GetNameAsync(int diasv) {
            return base.Channel.GetNameAsync(diasv);
        }
        
        public int ServiceGetCantidadP(string idproducto) {
            return base.Channel.ServiceGetCantidadP(idproducto);
        }
        
        public System.Threading.Tasks.Task<int> ServiceGetCantidadPAsync(string idproducto) {
            return base.Channel.ServiceGetCantidadPAsync(idproducto);
        }
        
        public int ServiceSetCantidadP(string idproducto, int newcantidad) {
            return base.Channel.ServiceSetCantidadP(idproducto, newcantidad);
        }
        
        public System.Threading.Tasks.Task<int> ServiceSetCantidadPAsync(string idproducto, int newcantidad) {
            return base.Channel.ServiceSetCantidadPAsync(idproducto, newcantidad);
        }
        
        public CapaGUI.ServiceProducto.Producto ServiceGetProductMasVendido() {
            return base.Channel.ServiceGetProductMasVendido();
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceProducto.Producto> ServiceGetProductMasVendidoAsync() {
            return base.Channel.ServiceGetProductMasVendidoAsync();
        }
        
        public CapaGUI.ServiceProducto.Producto ServiceGetClienteConMasCompras() {
            return base.Channel.ServiceGetClienteConMasCompras();
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceProducto.Producto> ServiceGetClienteConMasComprasAsync() {
            return base.Channel.ServiceGetClienteConMasComprasAsync();
        }
        
        public System.Data.DataSet ServiceGetConsultaProducto() {
            return base.Channel.ServiceGetConsultaProducto();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ServiceGetConsultaProductoAsync() {
            return base.Channel.ServiceGetConsultaProductoAsync();
        }
    }
}
