//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceVerificarUserPsw {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVerificarUserPsw.WebServiceInicioSesionSoap")]
    public interface WebServiceInicioSesionSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        CapaGUI.ServiceVerificarUserPsw.GetUserResponse GetUser(CapaGUI.ServiceVerificarUserPsw.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceVerificarUserPsw.GetUserResponse> GetUserAsync(CapaGUI.ServiceVerificarUserPsw.GetUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceinsertarUser", ReplyAction="*")]
        CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserResponse ServiceinsertarUser(CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceinsertarUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserResponse> ServiceinsertarUserAsync(CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceDeleteUser", ReplyAction="*")]
        CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserResponse ServiceDeleteUser(CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceDeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserResponse> ServiceDeleteUserAsync(CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscarUser", ReplyAction="*")]
        CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserResponse ServiceBuscarUser(CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscarUser", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserResponse> ServiceBuscarUserAsync(CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceVerificarUserPsw.GetUserRequestBody Body;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(CapaGUI.ServiceVerificarUserPsw.GetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contra;
        
        public GetUserRequestBody() {
        }
        
        public GetUserRequestBody(string user, string contra) {
            this.user = user;
            this.contra = contra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceVerificarUserPsw.GetUserResponseBody Body;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(CapaGUI.ServiceVerificarUserPsw.GetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetUserResult;
        
        public GetUserResponseBody() {
        }
        
        public GetUserResponseBody(int GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceinsertarUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceinsertarUser", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserRequestBody Body;
        
        public ServiceinsertarUserRequest() {
        }
        
        public ServiceinsertarUserRequest(CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceinsertarUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceVerificarUserPsw.User user;
        
        public ServiceinsertarUserRequestBody() {
        }
        
        public ServiceinsertarUserRequestBody(CapaGUI.ServiceVerificarUserPsw.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceinsertarUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceinsertarUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserResponseBody Body;
        
        public ServiceinsertarUserResponse() {
        }
        
        public ServiceinsertarUserResponse(CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ServiceinsertarUserResponseBody {
        
        public ServiceinsertarUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceDeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceDeleteUser", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserRequestBody Body;
        
        public ServiceDeleteUserRequest() {
        }
        
        public ServiceDeleteUserRequest(CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceDeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        public ServiceDeleteUserRequestBody() {
        }
        
        public ServiceDeleteUserRequestBody(string user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceDeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceDeleteUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserResponseBody Body;
        
        public ServiceDeleteUserResponse() {
        }
        
        public ServiceDeleteUserResponse(CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ServiceDeleteUserResponseBody {
        
        public ServiceDeleteUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceBuscarUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceBuscarUser", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserRequestBody Body;
        
        public ServiceBuscarUserRequest() {
        }
        
        public ServiceBuscarUserRequest(CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceBuscarUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        public ServiceBuscarUserRequestBody() {
        }
        
        public ServiceBuscarUserRequestBody(string user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceBuscarUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceBuscarUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserResponseBody Body;
        
        public ServiceBuscarUserResponse() {
        }
        
        public ServiceBuscarUserResponse(CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceBuscarUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CapaGUI.ServiceVerificarUserPsw.User ServiceBuscarUserResult;
        
        public ServiceBuscarUserResponseBody() {
        }
        
        public ServiceBuscarUserResponseBody(CapaGUI.ServiceVerificarUserPsw.User ServiceBuscarUserResult) {
            this.ServiceBuscarUserResult = ServiceBuscarUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceInicioSesionSoapChannel : CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceInicioSesionSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap>, CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap {
        
        public WebServiceInicioSesionSoapClient() {
        }
        
        public WebServiceInicioSesionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceInicioSesionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceInicioSesionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceInicioSesionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceVerificarUserPsw.GetUserResponse CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap.GetUser(CapaGUI.ServiceVerificarUserPsw.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public int GetUser(string user, string contra) {
            CapaGUI.ServiceVerificarUserPsw.GetUserRequest inValue = new CapaGUI.ServiceVerificarUserPsw.GetUserRequest();
            inValue.Body = new CapaGUI.ServiceVerificarUserPsw.GetUserRequestBody();
            inValue.Body.user = user;
            inValue.Body.contra = contra;
            CapaGUI.ServiceVerificarUserPsw.GetUserResponse retVal = ((CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap)(this)).GetUser(inValue);
            return retVal.Body.GetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceVerificarUserPsw.GetUserResponse> CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap.GetUserAsync(CapaGUI.ServiceVerificarUserPsw.GetUserRequest request) {
            return base.Channel.GetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceVerificarUserPsw.GetUserResponse> GetUserAsync(string user, string contra) {
            CapaGUI.ServiceVerificarUserPsw.GetUserRequest inValue = new CapaGUI.ServiceVerificarUserPsw.GetUserRequest();
            inValue.Body = new CapaGUI.ServiceVerificarUserPsw.GetUserRequestBody();
            inValue.Body.user = user;
            inValue.Body.contra = contra;
            return ((CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap)(this)).GetUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserResponse CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap.ServiceinsertarUser(CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserRequest request) {
            return base.Channel.ServiceinsertarUser(request);
        }
        
        public void ServiceinsertarUser(CapaGUI.ServiceVerificarUserPsw.User user) {
            CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserRequest inValue = new CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserRequest();
            inValue.Body = new CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserRequestBody();
            inValue.Body.user = user;
            CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserResponse retVal = ((CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap)(this)).ServiceinsertarUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserResponse> CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap.ServiceinsertarUserAsync(CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserRequest request) {
            return base.Channel.ServiceinsertarUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserResponse> ServiceinsertarUserAsync(CapaGUI.ServiceVerificarUserPsw.User user) {
            CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserRequest inValue = new CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserRequest();
            inValue.Body = new CapaGUI.ServiceVerificarUserPsw.ServiceinsertarUserRequestBody();
            inValue.Body.user = user;
            return ((CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap)(this)).ServiceinsertarUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserResponse CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap.ServiceDeleteUser(CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserRequest request) {
            return base.Channel.ServiceDeleteUser(request);
        }
        
        public void ServiceDeleteUser(string user) {
            CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserRequest inValue = new CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserRequest();
            inValue.Body = new CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserRequestBody();
            inValue.Body.user = user;
            CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserResponse retVal = ((CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap)(this)).ServiceDeleteUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserResponse> CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap.ServiceDeleteUserAsync(CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserRequest request) {
            return base.Channel.ServiceDeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserResponse> ServiceDeleteUserAsync(string user) {
            CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserRequest inValue = new CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserRequest();
            inValue.Body = new CapaGUI.ServiceVerificarUserPsw.ServiceDeleteUserRequestBody();
            inValue.Body.user = user;
            return ((CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap)(this)).ServiceDeleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserResponse CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap.ServiceBuscarUser(CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserRequest request) {
            return base.Channel.ServiceBuscarUser(request);
        }
        
        public CapaGUI.ServiceVerificarUserPsw.User ServiceBuscarUser(string user) {
            CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserRequest inValue = new CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserRequest();
            inValue.Body = new CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserRequestBody();
            inValue.Body.user = user;
            CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserResponse retVal = ((CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap)(this)).ServiceBuscarUser(inValue);
            return retVal.Body.ServiceBuscarUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserResponse> CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap.ServiceBuscarUserAsync(CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserRequest request) {
            return base.Channel.ServiceBuscarUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserResponse> ServiceBuscarUserAsync(string user) {
            CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserRequest inValue = new CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserRequest();
            inValue.Body = new CapaGUI.ServiceVerificarUserPsw.ServiceBuscarUserRequestBody();
            inValue.Body.user = user;
            return ((CapaGUI.ServiceVerificarUserPsw.WebServiceInicioSesionSoap)(this)).ServiceBuscarUserAsync(inValue);
        }
    }
}
