//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceVerificadorDatos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVerificadorDatos.WebServiceVerificarDatosSoap")]
    public interface WebServiceVerificarDatosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dto1 del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarDatosProducto", ReplyAction="*")]
        CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoResponse VerificarDatosProducto(CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarDatosProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoResponse> VerificarDatosProductoAsync(CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarDatosProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarDatosProducto", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoRequestBody Body;
        
        public VerificarDatosProductoRequest() {
        }
        
        public VerificarDatosProductoRequest(CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarDatosProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dto1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dto2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dto3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dto4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dto5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dto6;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string dto7;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string dto8;
        
        public VerificarDatosProductoRequestBody() {
        }
        
        public VerificarDatosProductoRequestBody(string dto1, string dto2, string dto3, string dto4, string dto5, string dto6, string dto7, string dto8) {
            this.dto1 = dto1;
            this.dto2 = dto2;
            this.dto3 = dto3;
            this.dto4 = dto4;
            this.dto5 = dto5;
            this.dto6 = dto6;
            this.dto7 = dto7;
            this.dto8 = dto8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarDatosProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarDatosProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoResponseBody Body;
        
        public VerificarDatosProductoResponse() {
        }
        
        public VerificarDatosProductoResponse(CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarDatosProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerificarDatosProductoResult;
        
        public VerificarDatosProductoResponseBody() {
        }
        
        public VerificarDatosProductoResponseBody(string VerificarDatosProductoResult) {
            this.VerificarDatosProductoResult = VerificarDatosProductoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceVerificarDatosSoapChannel : CapaGUI.ServiceVerificadorDatos.WebServiceVerificarDatosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceVerificarDatosSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceVerificadorDatos.WebServiceVerificarDatosSoap>, CapaGUI.ServiceVerificadorDatos.WebServiceVerificarDatosSoap {
        
        public WebServiceVerificarDatosSoapClient() {
        }
        
        public WebServiceVerificarDatosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceVerificarDatosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVerificarDatosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVerificarDatosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoResponse CapaGUI.ServiceVerificadorDatos.WebServiceVerificarDatosSoap.VerificarDatosProducto(CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoRequest request) {
            return base.Channel.VerificarDatosProducto(request);
        }
        
        public string VerificarDatosProducto(string dto1, string dto2, string dto3, string dto4, string dto5, string dto6, string dto7, string dto8) {
            CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoRequest inValue = new CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoRequest();
            inValue.Body = new CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoRequestBody();
            inValue.Body.dto1 = dto1;
            inValue.Body.dto2 = dto2;
            inValue.Body.dto3 = dto3;
            inValue.Body.dto4 = dto4;
            inValue.Body.dto5 = dto5;
            inValue.Body.dto6 = dto6;
            inValue.Body.dto7 = dto7;
            inValue.Body.dto8 = dto8;
            CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoResponse retVal = ((CapaGUI.ServiceVerificadorDatos.WebServiceVerificarDatosSoap)(this)).VerificarDatosProducto(inValue);
            return retVal.Body.VerificarDatosProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoResponse> CapaGUI.ServiceVerificadorDatos.WebServiceVerificarDatosSoap.VerificarDatosProductoAsync(CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoRequest request) {
            return base.Channel.VerificarDatosProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoResponse> VerificarDatosProductoAsync(string dto1, string dto2, string dto3, string dto4, string dto5, string dto6, string dto7, string dto8) {
            CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoRequest inValue = new CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoRequest();
            inValue.Body = new CapaGUI.ServiceVerificadorDatos.VerificarDatosProductoRequestBody();
            inValue.Body.dto1 = dto1;
            inValue.Body.dto2 = dto2;
            inValue.Body.dto3 = dto3;
            inValue.Body.dto4 = dto4;
            inValue.Body.dto5 = dto5;
            inValue.Body.dto6 = dto6;
            inValue.Body.dto7 = dto7;
            inValue.Body.dto8 = dto8;
            return ((CapaGUI.ServiceVerificadorDatos.WebServiceVerificarDatosSoap)(this)).VerificarDatosProductoAsync(inValue);
        }
    }
}
